In [2]:
import pandas as pd

meta = pd.read_parquet(r"E:\organ-chip-ai\data\raw\cell_painting\metadata.parquet")
index= pd.read_parquet(r"E:\organ-chip-ai\data\raw\cell_painting\index.parquet")
cp= pd.read_parquet(r"E:\organ-chip-ai\data\raw\cell_painting\cellprofiler_raw.parquet")
dino= pd.read_parquet(r"E:\organ-chip-ai\data\raw\cell_painting\dino_raw.parquet")

loading all datasets related to cell painting

In [8]:
print(meta.shape)
print(index.shape)
print(cp.shape)
print(dino.shape)

(21456, 24)
(2019342, 6)
(21455, 5671)
(21306, 4631)

this information is about the size of tabels of all four data (rows,columns)

In [9]:
meta.columns

Index(['Metadata_well_id', 'Metadata_source', 'Metadata_Plate',
       'Metadata_Concentration', 'Metadata_Compound',
       'Metadata_compound_target', 'Metadata_compound_pathway',
       'Metadata_compound_research_area',
       'Metadata_compound_clinical_information', 'Metadata_Well',
       'Metadata_row', 'Metadata_col', 'Metadata_mtt_lumi',
       'Metadata_ldh_abs_signal', 'Metadata_ldh_abs_background',
       'Metadata_ldh_abs', 'Metadata_mtt_normalized',
       'Metadata_ldh_normalized', 'Metadata_mtt_ridge_norm',
       'Metadata_ldh_ridge_norm', 'Metadata_OASIS_ID', 'Metadata_Perturbation',
       'Metadata_Log10Conc', 'Metadata_Count_Cells'],
      dtype='object')

In [21]:
index.columns
index.head(5)

,Metadata_Batch,Metadata_Plate,Metadata_Well,Metadata_Site,Channel,Filename
0,prod_26,plate_41002885,A01,1.0,Brightfield,s3://cellpainting-gallery/cpg0037-oasis/axiom/...
1,prod_26,plate_41002885,A01,2.0,Brightfield,s3://cellpainting-gallery/cpg0037-oasis/axiom/...
2,prod_26,plate_41002885,A01,3.0,Brightfield,s3://cellpainting-gallery/cpg0037-oasis/axiom/...
3,prod_26,plate_41002885,A01,4.0,Brightfield,s3://cellpainting-gallery/cpg0037-oasis/axiom/...
4,prod_26,plate_41002885,A01,5.0,Brightfield,s3://cellpainting-gallery/cpg0037-oasis/axiom/...

In [22]:
dino.columns
dino.head(5)

,Metadata_Plate,Metadata_Well,Metadata_source,Metadata_Concentration,Metadata_Compound,Metadata_compound_target,Metadata_compound_pathway,Metadata_compound_research_area,Metadata_compound_clinical_information,Metadata_row,...,Brightfield_759,Brightfield_760,Brightfield_761,Brightfield_762,Brightfield_763,Brightfield_764,Brightfield_765,Brightfield_766,Brightfield_767,Brightfield_768
0,plate_41002701,C21,assayworks_prod_25,33.5,Thalidomide,Autophagy; Ligands for E3 Ligase,Autophagy; PROTAC,Cancer; Inflammation/Immunology,Launched,2,...,-0.326069,1.009144,-0.159031,0.453206,0.463359,-0.750099,0.086075,-0.000049,0.596952,-0.177552
1,plate_41002879,O03,assayworks_prod_26,11.0,CP-532623,CETP,Metabolic Enzyme/Protease,Metabolic Disease,No Development Reported,14,...,-0.031619,0.929342,-0.303071,0.511530,0.453261,-0.825667,0.062867,0.026629,0.595824,-0.218642
2,plate_41002890,O09,assayworks_prod_26,33.5,Triclopyr,Fungal,Anti-infection,Others,No Development Reported,14,...,-0.338073,1.000662,-0.247761,0.252527,0.501299,-0.658067,0.034160,-0.049087,0.680024,-0.267192
3,plate_41002694,P03,assayworks_prod_25,1.0,Bezafibrate,PPAR,Cell Cycle/DNA Damage; Metabolic Enzyme/Protea...,Metabolic Disease; Cardiovascular Disease,Launched,15,...,-0.400490,0.949700,-0.198375,0.286987,0.471899,-0.670080,0.142744,-0.019730,0.568913,-0.248922
4,plate_41002905,J07,assayworks_prod_27,11.0,Compound_f92d6120,None,None,None,None,9,...,-0.092581,1.061058,-0.246802,0.394550,0.444711,-0.770457,0.037895,0.024986,0.605912,-0.184488

In [23]:
cp.columns
cp.head(5)

,Metadata_well_id,Metadata_source,Metadata_Plate,Metadata_Concentration,Metadata_Compound,Metadata_compound_target,Metadata_compound_pathway,Metadata_compound_research_area,Metadata_compound_clinical_information,Metadata_Well,...,Nuclei_Texture_Variance_RNA_10_02_256,Nuclei_Texture_Variance_RNA_10_03_256,Nuclei_Texture_Variance_RNA_3_00_256,Nuclei_Texture_Variance_RNA_3_01_256,Nuclei_Texture_Variance_RNA_3_02_256,Nuclei_Texture_Variance_RNA_3_03_256,Nuclei_Texture_Variance_RNA_5_00_256,Nuclei_Texture_Variance_RNA_5_01_256,Nuclei_Texture_Variance_RNA_5_02_256,Nuclei_Texture_Variance_RNA_5_03_256
0,assayworks_prod_26_p=plate_41002878_r=0_c=0,assayworks_prod_26,plate_41002878,100.0,"1,4-Dibromobenzene",None,None,None,No Development Reported,A01,...,3.0341,3.1077,2.9159,2.9334,2.9132,2.9362,2.9490,2.9822,2.9453,2.9872
1,assayworks_prod_26_p=plate_41002878_r=0_c=1,assayworks_prod_26,plate_41002878,100.0,"2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,9-Heptadecaflu...",None,None,None,None,A02,...,2.3187,2.3546,2.2794,2.2829,2.2794,2.2841,2.2871,2.2982,2.2865,2.3010
2,assayworks_prod_26_p=plate_41002878_r=0_c=2,assayworks_prod_26,plate_41002878,100.0,Calcifediol,Endogenous Metabolite; VD/VDR,Metabolic Enzyme/Protease; Vitamin D Related/N...,Metabolic Disease,Launched,A03,...,3.0126,3.0278,3.0800,3.0518,3.0812,3.0445,3.0351,3.0170,3.0377,3.0064
3,assayworks_prod_26_p=plate_41002878_r=0_c=3,assayworks_prod_26,plate_41002878,0.0,DMSO,None,None,None,None,A04,...,2.9056,2.9468,2.8565,2.8604,2.8541,2.8584,2.8663,2.8793,2.8639,2.8785
4,assayworks_prod_26_p=plate_41002878_r=0_c=4,assayworks_prod_26,plate_41002878,100.0,DHEA,Androgen Receptor; Endogenous Metabolite,Metabolic Enzyme/Protease; Vitamin D Related/N...,Endocrinology; Cancer,Launched,A05,...,2.3178,2.3498,2.2871,2.2889,2.2830,2.2899,2.2960,2.3024,2.2894,2.3049

In [8]:
meta["Metadata_Compound"].unique()

array(['DMSO', 'Compound_255ef47f', 'Primidone', ..., 'Compound_88f6068e',
       'Casoron', 'Linagliptin'], shape=(1086,), dtype=object)

In [33]:
meta["Metadata_Compound"].value_counts()
meta["Metadata_Compound"].value_counts().head(25)

Metadata_Compound
DMSO                              4849
Compound_04264751                   64
Ginkgo biloba extract               48
Vasopressin                         42
Titanocene dichloride               32
N,N-Dimethyl-4-toluidine            32
Myrcene                             32
Indole-3-carbinol                   28
Peramivir                           28
Sulfasalazine                       28
Valbenazine                         16
Casoron                             16
Geranyl acetate                     16
Cyclohexane-1,2,3,4,5,6-hexaol      16
Phenylbutazone                      16
Nystatin                            16
Clonidine                           16
2,6-Dichloro-4-nitroaniline         16
Infigratinib                        16
Pralsetinib                         16
Ezetimibe                           16
Ethyl methanesulfonate              16
Compound_9a411687                   16
Idelalisib                          16
Benzophenone                        16
Name: count, dtype: int64

In [14]:
meta["Metadata_compound_pathway"].value_counts().head(20)

Metadata_compound_pathway
Anti-infection                                                   1767
Others                                                           1344
Metabolic Enzyme/Protease                                         983
GPCR/G Protein; Neuronal Signaling                                904
Membrane Transporter/Ion Channel                                  516
Immunology/Inflammation                                           452
Membrane Transporter/Ion Channel; Neuronal Signaling              437
GPCR/G Protein                                                    377
Anti-infection; Metabolic Enzyme/Protease                         340
Protein Tyrosine Kinase/RTK                                       257
Neuronal Signaling                                                238
Cell Cycle/DNA Damage                                             201
GPCR/G Protein; Immunology/Inflammation; Neuronal Signaling       193
Anti-infection; Autophagy                                         174
Metabolic Enzyme/Protease; Vitamin D Related/Nuclear Receptor     172
Vitamin D Related/Nuclear Receptor                                167
Anti-infection; Cell Cycle/DNA Damage                             167
Apoptosis                                                         152
Apoptosis; Metabolic Enzyme/Protease                              124
GPCR/G Protein; Metabolic Enzyme/Protease; Neuronal Signaling     123
Name: count, dtype: int64

In [15]:
meta["Metadata_compound_target"].value_counts().head(20)

Metadata_compound_target
Others                              929
Antibiotic; Bacterial               609
COX                                 361
Biochemical Assay Reagents          304
Endogenous Metabolite               276
Adrenergic Receptor                 243
Fungal                              228
Histamine Receptor                  193
Potassium Channel                   170
Calcium Channel                     164
Parasite                            136
Cytochrome P450                     135
5-HT Receptor                       119
Apoptosis                           107
GABA Receptor                       106
HIV; Reverse Transcriptase          106
Dopamine Receptor                   102
Bacterial                           102
5-HT Receptor; Dopamine Receptor     93
Autophagy; Calcium Channel           90
Name: count, dtype: int64

In [16]:
meta["Metadata_Count_Cells"].describe()

count    21456.000000
mean       758.246225
std        144.458896
min          1.000000
25%        710.000000
50%        786.000000
75%        845.000000
max       1349.000000
Name: Metadata_Count_Cells, dtype: float64

In [36]:
meta_no_dmso = meta[
    meta["Metadata_Compound"] != "DMSO"
]

In [37]:
meta_no_dmso["Metadata_Compound"].nunique()

1085

In [38]:
meta_no_dmso["Metadata_Concentration"].unique()

array([4.56431545e-02, 1.00000000e+02, 4.10788387e-01, 3.50000000e+00,
       1.36929467e-01, 1.10000000e+01, 3.35000000e+01, 1.00000000e+00,
       2.00000000e+01, 6.69999981e+00, 8.21576789e-02, 6.99999988e-01,
       9.12863109e-03, 2.20000005e+00, 2.00000003e-01, 2.73858923e-02])

In [39]:
meta_no_dmso["Metadata_Concentration"].value_counts()

Metadata_Concentration
0.045643      2166
0.410788      2166
3.500000      2166
1.000000      2166
33.500000     2165
100.000000    2161
0.136929      1846
11.000000     1531
20.000000       30
6.700000        30
0.082158        30
0.700000        30
0.009129        30
2.200000        30
0.200000        30
0.027386        30
Name: count, dtype: int64

In [40]:
dose_effect = (
    meta_no_dmso
    .groupby("Metadata_Concentration")
    ["Metadata_Count_Cells"]
    .mean()
    .sort_index()
)

dose_effect

Metadata_Concentration
0.009129      828.000000
0.027386      806.833333
0.045643      816.364266
0.082158      787.266667
0.136929      770.462080
0.200000      626.800000
0.410788      749.344875
0.700000      730.600000
1.000000      786.492613
2.200000      719.533333
3.500000      795.075716
6.700000      660.500000
11.000000     775.946440
20.000000     698.266667
33.500000     669.945035
100.000000    674.773253
Name: Metadata_Count_Cells, dtype: float64

In [42]:
dose_count = (
    meta.groupby("Metadata_Compound")
        ["Metadata_Concentration"]
        .nunique()
)

dose_count.describe()

count    1086.000000
mean        7.992634
std         0.214543
min         1.000000
25%         8.000000
50%         8.000000
75%         8.000000
max         8.000000
Name: Metadata_Concentration, dtype: float64

In [43]:
meta.groupby(
    ["Metadata_Compound",
     "Metadata_Concentration"]
).size().describe()

count    8680.000000
mean        2.471889
std        52.027782
min         1.000000
25%         2.000000
50%         2.000000
75%         2.000000
max      4849.000000
dtype: float64

In [64]:
cp.columns[:50]

Index(['Metadata_well_id', 'Metadata_source', 'Metadata_Plate',
       'Metadata_Concentration', 'Metadata_Compound',
       'Metadata_compound_target', 'Metadata_compound_pathway',
       'Metadata_compound_research_area',
       'Metadata_compound_clinical_information', 'Metadata_Well',
       'Metadata_row', 'Metadata_col', 'Metadata_mtt_lumi',
       'Metadata_ldh_abs_signal', 'Metadata_ldh_abs_background',
       'Metadata_ldh_abs', 'Metadata_mtt_normalized',
       'Metadata_ldh_normalized', 'Metadata_mtt_ridge_norm',
       'Metadata_ldh_ridge_norm', 'Metadata_OASIS_ID', 'Metadata_Perturbation',
       'Metadata_Log10Conc', 'Metadata_Count_Cells', 'Metadata_Site_Count',
       'Metadata_Count_Cells_right', 'Metadata_Count_CellsIncludingEdges',
       'Metadata_Count_Cytoplasm', 'Metadata_Count_Nuclei',
       'Metadata_Count_NucleiIncludingEdges', 'Metadata_Object_Count',
       'Image_Granularity_10_AGP', 'Image_Granularity_10_Brightfield',
       'Image_Granularity_10_DNA', 'Image_Granularity_10_ER',
       'Image_Granularity_10_Mito', 'Image_Granularity_10_RNA',
       'Image_Granularity_11_AGP', 'Image_Granularity_11_Brightfield',
       'Image_Granularity_11_DNA', 'Image_Granularity_11_ER',
       'Image_Granularity_11_Mito', 'Image_Granularity_11_RNA',
       'Image_Granularity_12_AGP', 'Image_Granularity_12_Brightfield',
       'Image_Granularity_12_DNA', 'Image_Granularity_12_ER',
       'Image_Granularity_12_Mito', 'Image_Granularity_12_RNA',
       'Image_Granularity_13_AGP'],
      dtype='object')

this containd data related to MTT,LDH and Cells count. might be usefull for study of compound toxicity.

In [45]:
sum(cp.columns.str.startswith("Image_"))

np.int64(1168)

In [46]:
sum(cp.columns.str.startswith("Cells_"))

np.int64(1531)

In [48]:
sum(cp.columns.str.startswith("Nuclei_"))

np.int64(1422)

In [49]:
sum(cp.columns.str.startswith("Cytoplasm_"))

np.int64(1519)

These four commands to analyse the columns of cellprofiler dataset. no of feature related to image, cells, nuclei and cytoplasm.

In [59]:
meta[
[
"Metadata_mtt_normalized",
"Metadata_ldh_normalized",
"Metadata_Count_Cells"
]
].describe()

       Metadata_mtt_normalized  Metadata_ldh_normalized  Metadata_Count_Cells
count             21456.000000             21456.000000          21456.000000
mean                  0.973286                 0.023777            758.246225
std                   0.182568                 0.096243            144.458896
min                   0.008778                -1.042543              1.000000
25%                   0.930883                -0.035078            710.000000
50%                   0.991671                 0.002060            786.000000
75%                   1.063805                 0.059084            845.000000
max                   1.667246                 0.798054           1349.000000

In [60]:
meta[
[
"Metadata_Compound",
"Metadata_Concentration",
"Metadata_mtt_normalized",
"Metadata_ldh_normalized",
"Metadata_Count_Cells"
]
].sort_values(
    "Metadata_mtt_normalized"
).head(20)

,Metadata_Compound,Metadata_Concentration,Metadata_mtt_normalized,Metadata_ldh_normalized,Metadata_Count_Cells
18040,Compound_fee2a120,100.0,0.008778,0.391861,4
14185,Mitoxantrone,100.0,0.008778,0.592245,14
18042,Compound_fee2a120,100.0,0.008903,0.312583,1
7696,Trabectedin,100.0,0.009369,0.414028,7
14187,Mitoxantrone,100.0,0.009644,0.528440,28
6237,Baloxavir marboxil,100.0,0.010090,0.724301,1349
8826,Fluazinam,100.0,0.011531,0.208028,2
7698,Trabectedin,100.0,0.011870,0.354010,17
16234,Chlorothalonil,100.0,0.012435,0.264953,566
5725,Sunitinib,100.0,0.012539,0.551627,37
11103,Ferric maltol,100.0,0.013115,0.565140,473
19853,Amsacrine,100.0,0.013167,0.333951,5
11101,Ferric maltol,100.0,0.013693,0.289411,213
8828,Fluazinam,100.0,0.013740,0.149954,10
17287,Fidaxomicin,100.0,0.013740,0.289260,24
10924,Amodiaquine,100.0,0.013898,0.359505,5
9263,Nitrofurazone,100.0,0.014078,0.442627,3
19549,Neratinib,100.0,0.014420,0.364782,20
5727,Sunitinib,100.0,0.014838,0.502275,82
19852,Amsacrine,100.0,0.015047,0.624740,1

In [61]:
meta[
[
"Metadata_mtt_normalized",
"Metadata_ldh_normalized",
"Metadata_Count_Cells"
]
].corr()

,Metadata_mtt_normalized,Metadata_ldh_normalized,Metadata_Count_Cells
Metadata_mtt_normalized,1.000000,-0.276213,0.612198
Metadata_ldh_normalized,-0.276213,1.000000,-0.383440
Metadata_Count_Cells,0.612198,-0.383440,1.000000